ARG BASE_IMAGE
FROM ${BASE_IMAGE}

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libgtk-3-0 \
        libdbus-glib-1-2 && \
    rm -rf /var/lib/apt/lists/*

USER hermes
